#!/usr/bin/env python3
"""Generate internal/ui/emoji/table.go from the Python unicodedata tables.

Hand-writing an emoji table is how it ends up wrong: the names drift from the
official ones, the coverage stops wherever the author got bored, and nobody can
tell which of the two happened. This walks the codepoints Unicode gives an
emoji presentation by default -- the ones a terminal draws in colour without
being asked with a variation selector -- and takes the official name for each.

Run it with: python3 scripts/gen_emoji.py > internal/ui/emoji/table.go

The set is limited to what the running Python's unicodedata knows, so a build
on an older Python simply produces fewer entries rather than wrong ones.
"""
import sys
import unicodedata

# Emoji_Presentation=Yes, as ranges. Everything here is drawn in colour by a
# terminal that draws emoji at all; the text-presentation characters (which
# need U+FE0F to become pictures) are deliberately left out, because half of
# them arrive as monochrome glyphs and the picker looks broken.
RANGES = [
    (0x231A, 0x231B), (0x23E9, 0x23EC), (0x23F0, 0x23F0), (0x23F3, 0x23F3),
    (0x25FD, 0x25FE), (0x2614, 0x2615), (0x2648, 0x2653), (0x267F, 0x267F),
    (0x2693, 0x2693), (0x26A1, 0x26A1), (0x26AA, 0x26AB), (0x26BD, 0x26BE),
    (0x26C4, 0x26C5), (0x26CE, 0x26CE), (0x26D4, 0x26D4), (0x26EA, 0x26EA),
    (0x26F2, 0x26F3), (0x26F5, 0x26F5), (0x26FA, 0x26FA), (0x26FD, 0x26FD),
    (0x2705, 0x2705), (0x270A, 0x270B), (0x2728, 0x2728), (0x274C, 0x274C),
    (0x274E, 0x274E), (0x2753, 0x2755), (0x2757, 0x2757), (0x2795, 0x2797),
    (0x27B0, 0x27B0), (0x27BF, 0x27BF), (0x2B1B, 0x2B1C), (0x2B50, 0x2B50),
    (0x2B55, 0x2B55),
    (0x1F300, 0x1F320), (0x1F32D, 0x1F335), (0x1F337, 0x1F37C),
    (0x1F37E, 0x1F393), (0x1F3A0, 0x1F3CA), (0x1F3CF, 0x1F3D3),
    (0x1F3E0, 0x1F3F0), (0x1F3F4, 0x1F3F4), (0x1F3F8, 0x1F43E),
    (0x1F440, 0x1F440), (0x1F442, 0x1F4FC), (0x1F4FF, 0x1F53D),
    (0x1F54B, 0x1F54E), (0x1F550, 0x1F567), (0x1F57A, 0x1F57A),
    (0x1F595, 0x1F596), (0x1F5A4, 0x1F5A4), (0x1F5FB, 0x1F64F),
    (0x1F680, 0x1F6C5), (0x1F6CC, 0x1F6CC), (0x1F6D0, 0x1F6D2),
    (0x1F6D5, 0x1F6D7), (0x1F6EB, 0x1F6EC), (0x1F6F4, 0x1F6FC),
    (0x1F7E0, 0x1F7EB), (0x1F90C, 0x1F93A), (0x1F93C, 0x1F945),
    (0x1F947, 0x1F9FF), (0x1FA70, 0x1FA74), (0x1FA78, 0x1FA7A),
    (0x1FA80, 0x1FA86), (0x1FA90, 0x1FAA8), (0x1FAB0, 0x1FAB6),
    (0x1FAC0, 0x1FAC2), (0x1FAD0, 0x1FAD6),
]

# Categories, in the order the picker shows them. A codepoint takes the first
# range it falls into, so the order of this list is the order of the tabs.
CATEGORIES = [
    ("Smileys", [(0x1F600, 0x1F64F), (0x1F910, 0x1F92F), (0x1F970, 0x1F97A),
                 (0x1F9D0, 0x1F9D0), (0x1FAE0, 0x1FAE7)]),
    ("People", [(0x1F440, 0x1F450), (0x1F464, 0x1F487), (0x1F574, 0x1F596),
                (0x1F645, 0x1F64F), (0x1F6C0, 0x1F6CC), (0x1F933, 0x1F93A),
                (0x1F9B0, 0x1F9CF), (0x1FAF0, 0x1FAF6), (0x270A, 0x270B)]),
    ("Nature", [(0x1F300, 0x1F320), (0x1F400, 0x1F43E), (0x1F330, 0x1F335),
                (0x1F337, 0x1F343), (0x1F980, 0x1F9AE), (0x1F324, 0x1F32C),
                (0x2600, 0x26D4), (0x2728, 0x2728), (0x1F7E0, 0x1F7EB)]),
    ("Food", [(0x1F345, 0x1F37F), (0x1F950, 0x1F96F), (0x1F32D, 0x1F32F),
              (0x1FAD0, 0x1FAD9), (0x1F9C0, 0x1F9CB)]),
    ("Activity", [(0x1F380, 0x1F3CA), (0x1F3CF, 0x1F3F0), (0x1F939, 0x1F94F),
                  (0x26BD, 0x26BE), (0x1F3AE, 0x1F3B7)]),
    ("Travel", [(0x1F680, 0x1F6FF), (0x1F5FB, 0x1F5FF), (0x1F3E0, 0x1F3F4),
                (0x2708, 0x2708), (0x26F5, 0x26FD)]),
    ("Objects", [(0x1F4A0, 0x1F4FF), (0x1F500, 0x1F53D), (0x1F9F0, 0x1F9FF),
                 (0x1FA70, 0x1FAA8), (0x231A, 0x23F3), (0x1F550, 0x1F567)]),
]


def shortcode(name):
    out = []
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in " -_":
            out.append("_")
    code = "".join(out)
    while "__" in code:
        code = code.replace("__", "_")
    return code.strip("_")


def category(cp):
    for name, ranges in CATEGORIES:
        for lo, hi in ranges:
            if lo <= cp <= hi:
                return name
    return "Symbols"


def main():
    seen = set()
    rows = []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            if cp in seen:
                continue
            name = unicodedata.name(chr(cp), "")
            if not name:
                continue
            seen.add(cp)
            rows.append((chr(cp), name.lower(), shortcode(name), category(cp)))

    used = {}
    out = sys.stdout
    out.write('''// Code generated by scripts/gen_emoji.py; DO NOT EDIT.

package emoji

// entries is every emoji the picker offers, with the official Unicode name
// behind it. Names rather than a hand-written keyword list: the name is what
// people actually search for ("thinking", "party", "rocket"), it is the same
// string every other client shows, and it cannot drift from the character it
// describes.
var entries = []Entry{
''')
    for char, name, code, cat in rows:
        n = used.get(code, 0)
        used[code] = n + 1
        if n:
            code = "%s_%d" % (code, n + 1)
        out.write('\t{Char: %s, Name: %s, Code: %s, Category: %s},\n' % (
            gostr(char), gostr(name), gostr(code), gostr(cat)))
    out.write('}\n')


def gostr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
